#!/bin/bash
# This script helps the admin to automate the process of creating user account with easy
# Make sure the script is being executed with superuser privileges
if [[ "${UID}" -ne 0 ]]
then 
	echo 'Please run with sudo or as root'
	exit 1
fi
# Get the username ( login )
read -p 'Enter the username to create: ' USER_NAME
# Get the real name 
read -p 'Enter the real name of the person of the specific username: ' COMMENT
# Create the user with the password 
read -p 'Enter your password: ' PASSWORD
# create the account 
/sbin/useradd -c "${COMMENT}" -m ${USER_NAME}
# check to see if the useradd command succeeded 
if [[ "${?}" -ne 0 ]]
then
	echo "[+] The user account was not created."
	exit 1
fi
# Set the password 
echo "${USER_NAME}:${PASSWORD}" | /sbin/chpasswd
# Check to see if the passwd command succeded 
if [[ "${?}" -ne 0 ]]
then 
	echo "[+] The password was not changed "
	exit 1
fi
# Force password change on first login 
passwd -e ${USER_NAME}
# Display the username, password and the host where the user was created
echo
echo 'username:'
echo "${USER_NAME}"
echo 'password'
echo "${PASSWORD}"
echo 'HOST'
echo "${HOSTNAME}"
exit 0
